version: '3'
services:
  ssh:
    image: alpine:latest
    ports:
      - "22:22"
    command: |
      sh -c '
      apk add --no-cache openssh &&
      echo "PermitRootLogin yes" >> /etc/ssh/sshd_config &&
      ssh-keygen -A &&
      /usr/sbin/sshd -D'
